# File: .gitlab-ci.yml
# License: Part of the PIRA proect. Licensed under BSD 3 clause license. See LICENSE.txt file at https://github.com/jplehr/pira/LICENSE.txt
# Description: File to configure our Gitlab CI

# Stages
stages:
  - download
  - build
  - test
  - install

.lb-setup: &lb-setup
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/gitlab_rsa
  - module use /home/groups/sc/modules/modulefiles
  - module load gcc/8 git clang/9.0 cmake python/3

.lb-tear-down: &lb-tear-down
  - echo $SSH_AUTH_SOCK
  - rm -rf $(dirname $(echo $SSH_AUTH_SOCK))
  - ssh-agent -k

run-dowload:
  stage: download
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: clone
  script:
    - git clone https://github.com/nlohmann/json
    - *lb-tear-down

run-build:
  stage: build
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: fetch
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/cgcollector-test-install -DJSON_INCLUDE_PATH=../json/single_include ..
    - make -j $(cat /proc/cpuinfo | grep processor | wc -l)
    - echo $PWD
    - ls test
    - *lb-tear-down

run-test:
  stage: test
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - ls
    - ls build
    - ls build/test
    - cd test && bash run_simple_test.sh
    - *lb-tear-down

run-install:
  stage: install
  tags:
    - general
  before_script: *lb-setup
  variables:
    GIT_STRATEGY: none
  script:
    - cd build
    - make install
    - stat /tmp/cgcollector-test-install/bin/cgcollector
    - stat /tmp/cgcollector-test-install/bin/cgmerge
    - export LD_LIBRARY_PATH=/tmp/cgcollector-test-install/lib:$LD_LIBRARY_PATH
    - /tmp/cgcollector-test-install/bin/cgcollector --help
    - rm -r /tmp/cgcollector-*
    - *lb-tear-down


