name: MetaCG CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cmake
      run: cmake -B build -S .
    - name: build
      run: cmake --build build --parallel

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: "container/full-build"
          tags: metacg-devel:latest 
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
      - name: Run MCG library tests 
        uses: addnab/docker-run-action@v3
        with: 
          image: metacg-devel:latest
          run: /opt/metacg/metacg/build/graph/test/unit/libtests
      - name: Run PGIS library tests 
        uses: addnab/docker-run-action@v3
        with: 
          image: metacg-devel:latest
          run: /opt/metacg/metacg/build/pgis/test/unit/pgistests
